app = "aincrad-digital-marketing"
primary_region = "fra"

[build.args]
  GO_VERSION = "1.24"

[env]
  LOG_PATH = "/logs"
  PORT = "8080"

[http_service]
  auto_start_machines = true
  auto_stop_machines = "suspend"
  force_https = true
  internal_port = 8080
  min_machines_running = 1
  processes = ["app"]

[[mounts]]
  source = "log_volume"
  destination = "/logs"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
