propeller:
  aid: "YOUR_AID"
  tid: "YOUR_TID"
  postback_url: "http://ad.propellerads.com/conversion.php"

galaksion:
  cid: "46704"
  postback_url: "http://postback.report/postback"

popcash:
  aid: "494669"
  type: "1"
  postback_url: "https://ct.popcash.net/click"

clickadilla:
  postback_url: "https://tracking.clickadilla.com/in/postbacks"
  token: "m96gRV"

bot_filter:
  allow_countries: ["ID"]
  allow_mobile_only: false
  rate_limit_max: 10
  rate_limit_window_sec: 10
  log_allowed: false
  log_blocked: true
  blacklist_ua:
    - "curl"
    - "bot"
    - "spider"
    - "crawler"
    - "python"
    - "scrapy"
    - "headless"
  blacklist_ip_prefix: []
  # Exact match

products:
  - name: "Shopee Direct - Anwar"
    url: "https://s.shopee.co.id/50QdGhpr5Y?sub_id={spot_id}-{type_ads}-{zoneid}-{domain}"
    percentage: 33

  - name: "Shopee Direct - Rima"
    url: "https://s.shopee.co.id/40X6O25UZO?sub_id={spot_id}-{type_ads}-{zoneid}-{domain}"
    percentage: 22

  - name: "Accesstrade - Tiktok"
    url: "https://atid.me/go/FiOFvotq?sub_id={subid}&type_ads={type_ads}&utm_source={spot_id}-{type_ads}-{zoneid}-{domain}"
    percentage: 5

  - name: "Accesstrade - Shopee ID - Non KOL"
    url: "https://atid.me/002bc7002lt5?sub_id={subid}&type_ads={type_ads}&utm_source={spot_id}-{type_ads}-{zoneid}-{domain}"
    percentage: 6

  - name: "Accesstrade - Shopee ID - KOL Tier 1"
    url: "https://atid.me/0095ot002lt5?sub_id={subid}&type_ads={type_ads}&utm_source={spot_id}-{type_ads}-{zoneid}-{domain}"
    percentage: 6

  - name: "Accesstrade - Shopee ID - KOL Tier 2"
    url: "https://atid.me/002d1g002lt5?sub_id={subid}&type_ads={type_ads}&utm_source={spot_id}-{type_ads}-{zoneid}-{domain}"
    percentage: 6

  - name: "Tokopedia Direct - Kejar Diskon"
    url: "https://tk.tokopedia.com/ZSUhK4xP7?sub_id={spot_id}-{type_ads}-{zoneid}-{domain}"
    percentage: 3

  - name: "Facebook - Shopee"
    url: "https://s.shopee.co.id/an_redir?origin_link=https%3A%2F%2Fshopee.co.id%2Fproduct%2F1059640472%2F28276426642%3Fgads_t_sig%3DVTJGc2RHVmtYMTlxTFVSVVRrdENkVHQ3ZkZSUTMrR3pBWmZZNzdrcnRBMy9yU1E0WDRTanRrWWlyYUZXdFh6Y1dHREFvUy9heDhQNHlkMG5WSmpGVmt1ZmVXU29VTFRFR29lNGJBaVhWTGpvUWVwblhXdlBISUJkSlljMlZuZFZFeXZ2N1JwbUtRNkkyL3loV25PYVRBPT0&sm=fb_partner&affiliate_id=11313581024"
    percentage: 3

  - name: "Lazada Direct - Recommend Bonus offer - ALP"
    url: "https://c.lazada.co.id/t/c.cUsrdU?sub_id={spot_id}-{type_ads}-{zoneid}-{domain}"
    percentage: 3

  - name: "Lazada Direct - Buy at Best Price"
    url: "https://c.lazada.co.id/t/c.cUsrd8?sub_id={spot_id}-{type_ads}-{zoneid}-{domain}"
    percentage: 3

#  - name: "Agoda Direct - Text Link"
#    url: "https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1950504&hl=id-id&city=8691&sub_id={spot_id}-{type_ads}-{zoneid}-{domain}"
#    percentage: 4

#  - name: "Accesstrade - Shopee ID KOL Tier 1"
#    url: "https://atid.me/0095ot002lt5?utm_source={spot_id}-{type_ads}-{zoneid}-{domain}"
#    percentage: 2

#  - name: "Accesstrade - Shopee ID KOL Tier 2"
#    url: "https://atid.me/002d1g002lt5?utm_source={spot_id}-{type_ads}-{zoneid}-{domain}"
#    percentage: 2

#  - name: "Involve - Lapak Gaming"
#    url: "https://invl.app/clmzh3h?sub_id={spot_id}-{type_ads}-{zoneid}-{domain}"
#    percentage: 2

#  - name: "Involve - Traveloka"
#    url: "https://invl.me/clmzh4l?sub_id={spot_id}-{type_ads}-{zoneid}-{domain}"
#    percentage: 1

#  - name: "Ecomobi - Tiktok Shop"
#    url: "https://goeco.mobi/IZ8PRcbo?sub1={spot_id}-{type_ads}-{zoneid}-{domain}"
#    percentage: 1
