propeller:
  aid: "YOUR_AID"
  tid: "YOUR_TID"
  postback_url: "http://ad.propellerads.com/conversion.php"

galaksion:
  cid: "46704"
  postback_url: "http://postback.report/postback"

popcash:
  aid: "494669"
  type: "1"
  postback_url: "https://ct.popcash.net/click"

clickadilla:
  postback_url: "https://tracking.clickadilla.com/in/postbacks/"
  token: "m96gRV"

bot_filter:
  allow_countries: ["ID"]
  allow_mobile_only: true
  rate_limit_max: 10
  rate_limit_window_sec: 10
  log_allowed: false
  log_blocked: true
  blacklist_ua:
    - "curl"
    - "bot"
    - "spider"
    - "crawler"
    - "python"
    - "scrapy"
    - "headless"
  blacklist_ip_prefix: []
  # Exact match

products:
  - name: "Shopee Direct - Anwar"
    url: "https://s.shopee.co.id/5VLlFD7dZe?sub_id={campaign_id}-{spot_id}-{type_ads}-{domain}"
    percentage: 28

  - name: "Shopee Direct - Rima"
    url: "https://s.shopee.co.id/40X6O25UZO?sub_id={campaign_id}-{spot_id}-{type_ads}-{domain}"
    percentage: 18

  - name: "Accesstrade - Shopee ID - Komisi Xtra - KOL Tier 1"
    url: "https://atid.me/go/Ge9YbZ4P?utm_source={campaign_id}-{spot_id}-{type_ads}-{domain}"
    percentage: 18

  - name: "Agoda Direct - Text Link"
    url: "https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1950504&hl=id-id&city=8691"
    percentage: 6

  - name: "Accesstrade - Shopee ID KOL Tier 1"
    url: "https://atid.me/0095ot002lt5?utm_source={campaign_id}-{spot_id}-{type_ads}-{domain}"
    percentage: 5

  - name: "Lazada Direct - 9.9 Mega Brand Sale - Bonus offer"
    url: "https://c.lazada.co.id/t/c.c1Yk9D?sub_id1={spot_id}&sub_id2={sub_id}&sub_id3={type_ads}&sub_aff_id={sub_id}"
    percentage: 3

  - name: "Accesstrade - Lazada Kol"
    url: "https://atid.me/0082ly002lt5?utm_source={campaign_id}-{spot_id}-{type_ads}-{domain}"
    percentage: 2

  - name: "Ecomobi - Tiktok Shop"
    url: "https://goeco.mobi/IZ8PRcbo?sub1={campaign_id}-{spot_id}-{type_ads}-{domain}"
    percentage: 1

  - name: "Involve - Lapak Gaming"
    url: "https://invl.app/clmzh3h"
    percentage: 10

  - name: "Involve - Traveloka"
    url: "https://invl.me/clmzh4l"
    percentage: 3
